hora = int(input("Entre com a quantidade de horas trabalhadas no mes: "))
valor = int(input("Qual o valor da hora trabalhada: "))
salario = (hora*valor)
imposto = salario*(11/100)
inss = salario*(8/100)
sind = salario*(5/100)
liquido=salario-(imposto+inss+sind)
print(f"+ Salário Bruto: {salario}")
print(f"IR (11%) : R$ {imposto}")
print(f"INSS (8%) : R$ {inss}")
print(f"Sindicato (5%) : R$ {sind}")
print(f"= Salário liquido: R$ {liquido}")